Abort and exit nonzero if command gets error

diff --git a/bin/foreach b/bin/foreach
--- a/bin/foreach
+++ b/bin/foreach
@@ -30,7 +30,12 @@
 # POSSIBILITY OF SUCH DAMAGE.
 
 CMD=$@
-for MOD in $(./bin/repos) ; do
-  env MODULE=${MOD} /bin/sh -c "echo '-------- ${MOD} --------' && cd ${MOD} && ${CMD}"
-done
 
+err_exit() {
+  echo "command exited w/ error, foreach exiting"
+  exit 1
+}
+
+for MOD in $(./bin/repos) ; do
+  env MODULE=${MOD} /bin/sh -c "echo '-------- ${MOD} --------' && cd ${MOD} && ${CMD}" || err_exit
+done
